options:
  merge-default-rules: true
  formatter: stylish
rules:
  no-ids: 0
  property-sort-order:
    - 1
    - ignore-custom-properties: true
      order: smacss
  force-pseudo-nesting: 0
  quotes:
    - 1
    - style: double